=== uji-ros-pkg/underwater_simulation/UWSim/data/scenes/UWSimScene.dtd
<!ELEMENT UWSimScene (oceanState?,simParams?,camera?,vehicle*,object*,rosInterfaces?)>

<!-- elementos oceanScene -->
<!ELEMENT oceanState (windx?,windy?,windSpeed?,depth?,reflectionDamping?,waveScale?,isNotChoppy?,choppyFactor?,crestFoamHeight?,oceanSurfaceHeight?,fog?,color?,attenuation?)>
<!ELEMENT simParams (disableShaders?,resw?,resh?,offsetp?,offsetr?,enablePhysics?,gravity?,physicsWater?)>
<!ELEMENT vehicle (name,file,jointValues?,position?,orientation?,virtualCamera*, rangeSensor*, objectPicker*, imu*, pressureSensor*, gpsSensor*, dvlSensor*, virtualRangeImage*,multibeamSensor*, simulatedDevices?)>
<!ELEMENT virtualCamera (name,relativeTo,resw?,resh?,position?,orientation?,baseline?,frameId?, parameters?, showpath?)>
<!ELEMENT virtualRangeImage (name,relativeTo,resw?,resh?,position?,orientation?,parameters?)>
<!ELEMENT rangeSensor (name,relativeTo,range,visible?,position?,orientation?)>
<!ELEMENT objectPicker (name,relativeTo,range,position?,orientation?)>
<!ELEMENT imu (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT pressureSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT gpsSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT dvlSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT multibeamSensor (name,relativeTo,position?,orientation?, initAngle,finalAngle, angleIncr,range)>
<!ELEMENT camera (freeMotion?,objectToTrack?,fov?,aspectRatio?,near?,far?,position?,lookAt?) >
<!ELEMENT object (name,file,position,orientation,offsetp?,offsetr?,physics?)>
<!ELEMENT rosInterfaces ((ROSOdomToPAT*)?, (PATToROSOdom*)?, (ArmToROSJointState*)?, (ROSJointStateToArm*)?, (VirtualCameraToROSImage*)?, (ROSImageToHUD*)?,(ROSTwistToPAT*)?, (RangeSensorToROSRange*)?, (ROSPoseToPAT*)?, (ImuToROSImu*)?, (PressureSensorToROS*)?, (GPSSensorToROS*)?, (DVLSensorToROS*)?, (RangeImageSensorToROSImage*)?,(multibeamSensorToLaserScan*)?, (SimulatedDeviceROS*)?)>

<!-- elementos comunes -->
<!ELEMENT position (x,y,z)>
<!ELEMENT orientation (r,p,y)>
<!ELEMENT offsetp (x,y,z)>
<!ELEMENT offsetr (x,y,z)>
<!ELEMENT lookAt (x,y,z)>
<!ELEMENT color (r,g,b)>

<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>
<!ELEMENT r (#PCDATA)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT std (#PCDATA)>


<!-- elementos oceanState -->
<!ELEMENT windx (#PCDATA)>
<!ELEMENT windy (#PCDATA)>
<!ELEMENT windSpeed (#PCDATA)>
<!ELEMENT depth (#PCDATA)>
<!ELEMENT reflectionDamping (#PCDATA)>
<!ELEMENT waveScale (#PCDATA)>
<!ELEMENT isNotChoppy (#PCDATA)>
<!ELEMENT choppyFactor (#PCDATA)>
<!ELEMENT crestFoamHeight (#PCDATA)>
<!ELEMENT oceanSurfaceHeight (#PCDATA)>
<!ELEMENT fog (density,color)>
<!ELEMENT attenuation (r,g,b)>

<!ELEMENT density (#PCDATA)>

<!-- elementos simParams -->
<!ELEMENT disableShaders (#PCDATA)>
<!ELEMENT eye_in_hand (#PCDATA)>
<!ELEMENT resw (#PCDATA)>
<!ELEMENT resh (#PCDATA)>
<!ELEMENT enablePhysics (#PCDATA)>
<!ELEMENT gravity (x,y,z)>
<!ELEMENT physicsWater (size,position,resolution)>
<!ELEMENT size (minX,maxX,minY,maxY,minZ,maxZ)>
<!ELEMENT resolution (#PCDATA)>
<!ELEMENT minX (#PCDATA)>
<!ELEMENT maxX (#PCDATA)>
<!ELEMENT minY (#PCDATA)>
<!ELEMENT maxY (#PCDATA)>
<!ELEMENT minZ (#PCDATA)>
<!ELEMENT maxZ (#PCDATA)>

<!--elementos camera -->
<!ELEMENT freeMotion (#PCDATA)>
<!ELEMENT fov (#PCDATA)>
<!ELEMENT aspectRatio (#PCDATA)>
<!ELEMENT near (#PCDATA)>
<!ELEMENT far (#PCDATA)>

<!ELEMENT objectToTrack (#PCDATA)>

<!-- elementos virtualCamera -->
<!ELEMENT relativeTo (#PCDATA)>
<!ELEMENT parameters (fx,fy,x0,y0,f,n,k)>

<!ELEMENT fx (#PCDATA)>
<!ELEMENT fy (#PCDATA)>
<!ELEMENT x0 (#PCDATA)>
<!ELEMENT y0 (#PCDATA)>
<!ELEMENT f (#PCDATA)>
<!ELEMENT n (#PCDATA)>
<!ELEMENT k (#PCDATA)>
<!ELEMENT baseline (#PCDATA)>
<!ELEMENT frameId (#PCDATA)>
<!ELEMENT showpath (#PCDATA)>

<!--elementos rangeSensor -->
<!ELEMENT range (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!--elementos multibeamSensor -->
<!ELEMENT initAngle (#PCDATA)>
<!ELEMENT finalAngle (#PCDATA)>
<!ELEMENT angleIncr (#PCDATA)>

<!-- elementos vehicle -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT jointValues (joint+)>

<!ELEMENT joint (#PCDATA)>

<!-- elementos rosinterfaces -->
<!ELEMENT ROSOdomToPAT (topic,vehicleName, visualize?)>
<!ELEMENT PATToROSOdom  (topic, vehicleName, rate?)>
<!ELEMENT ArmToROSJointState  (topic, vehicleName, rate?)>
<!ELEMENT ROSJointStateToArm  (topic,vehicleName)>
<!ELEMENT VirtualCameraToROSImage (cameraName,imageTopic,infoTopic,rate?,depth?)>
<!ELEMENT RangeImageSensorToROSImage (cameraName,imageTopic,infoTopic,rate?)>
<!ELEMENT RangeSensorToROSRange (name,topic,rate?)>
<!ELEMENT ROSImageToHUD (width,height,posx?,posy?,scale?,blackWhite?,imageTopic,infoTopic?)>
<!ELEMENT ROSTwistToPAT (topic,vehicleName)>
<!ELEMENT ROSPoseToPAT (topic,vehicleName)>
<!ELEMENT ImuToROSImu (name, topic, rate?)>
<!ELEMENT PressureSensorToROS (name, topic, rate?)>
<!ELEMENT GPSSensorToROS (name, topic, rate?)>
<!ELEMENT DVLSensorToROS (name, topic, rate?)>
<!ELEMENT multibeamSensorToLaserScan (name, topic, rate?)>

<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT posx (#PCDATA)>
<!ELEMENT posy (#PCDATA)>
<!ELEMENT blackWhite (#PCDATA)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT vehicleName (#PCDATA)>
<!ELEMENT rate (#PCDATA)>
<!ELEMENT cameraName (#PCDATA)>
<!ELEMENT imageTopic (#PCDATA)>
<!ELEMENT infoTopic (#PCDATA)>
<!ELEMENT visualize (#PCDATA)>

<!-- elementos vcamtoROSImage -->
<!ELEMENT cam (#PCDATA)>
<!ELEMENT info (#PCDATA)>

<!-- elementos physics -->
<!ELEMENT physics (mass?,inertia?,collisionShapeType?,linearDamping?,angularDamping?,isKinematic? , minLinearLimit?, maxLinearLimit?,minAngularLimit?,maxAngularLimit?)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT inertia (x,y,z)>
<!ELEMENT collisionShapeType (#PCDATA)>
<!ELEMENT linearDamping (#PCDATA)>
<!ELEMENT angularDamping (#PCDATA)>
<!ELEMENT minLinearLimit (x,y,z)>
<!ELEMENT maxLinearLimit (x,y,z)>
<!ELEMENT isKinematic (#PCDATA)>
<!ELEMENT minAngularLimit (x,y,z)>
<!ELEMENT maxAngularLimit (x,y,z)>


<!-- simulatedDevices -->
<!ELEMENT simulatedDevices (
echo*
)>
<!ELEMENT SimulatedDeviceROS (
echoROS?
)>

<!ELEMENT echo (name, info )>
<!ELEMENT echoROS (name, topic, rate?)>

=== uji-ros-pkg/underwater_simulation/UWSim/data/scenes/cirs.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
  <oceanState>
    <windx> 0.04 </windx>
    <windy> 0.04 </windy>
    <windSpeed> 12 </windSpeed>
    <depth> 1000 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 1e-7 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> 2.5 </choppyFactor>
    <crestFoamHeight> 2.2 </crestFoamHeight>
    <oceanSurfaceHeight> 0 </oceanSurfaceHeight>
    <fog>
      <density> 0.1</density>
      <color>
	<r>0</r>
	<g>0.05</g>
	<b>0.3</b>
      </color>
    </fog>
    <color>
      <r>0.0</r>
      <g>0.05</g>
      <b>0.3</b>
    </color>
    <attenuation>
      <r>0.015</r>
      <g>0.0075 </g>
      <b> 0.005 </b>
    </attenuation>
  </oceanState>
  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 800 </resw>
    <resh> 600 </resh>
    <offsetp>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </offsetp>
    <offsetr>
      <x> 3.14</x>
      <y> 0</y>
      <z> -1.57 </z>
    </offsetr>
    <enablePhysics> 1 </enablePhysics>
  </simParams>
  <camera>
    <freeMotion> 1 </freeMotion>
    <objectToTrack>girona500/base_link</objectToTrack>
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 1 </near>
    <far> 10000 </far>
    <position>
      <x>-5</x>
      <y>-5 </y>
      <z>8 </z>
    </position> 
    <lookAt>
      <x>0</x>
      <y>0 </y>
      <z>0 </z>
    </lookAt>
  </camera>

  <vehicle>
    <name>girona500</name>
    <file>data/scenes/g500ARM5.urdf</file>
    <jointValues>
      <joint> 0 </joint>
      <joint> 0</joint>
      <joint> 2.2 </joint>
      <joint> 0 </joint>
      <joint>0.3 </joint>
    </jointValues>
    <position>
      <x> 0</x>
      <y> 0 </y>
      <z> 2.0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
    <virtualCamera>
      <name>bowtech1</name>
      <relativeTo>part0</relativeTo>
      <resw> 320 </resw>
      <resh> 240 </resh>
      <position>
        <x>-0.2</x>
        <y> -0.1 </y>
        <z> 0 </z>
      </position>
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>1.57 </y>
      </orientation>
      <!-- draws the FOV of the camera projected on the scene each 2 seconds -->
      <!-- <showpath>2</showpath>  -->
    </virtualCamera>
    <virtualCamera>
      <name>bowtech2</name>
      <relativeTo>part0</relativeTo>
      <resw> 320</resw>
      <resh> 240 </resh>
      <position>
        <x>-0.2</x>
        <y> 0.1 </y>
        <z> 0 </z>
      </position>  
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>1.57 </y>
      </orientation>
    </virtualCamera>
    <rangeSensor>
      <name>sonar</name>
      <relativeTo>part0</relativeTo>
      <range>10</range>
      <visible>0</visible>
      <position>
        <x>-0.3</x>
        <y>0</y>
        <z>0</z>
      </position>  
      <orientation>
        <r>0</r>
        <p>1.57</p>
        <y>0</y>
      </orientation>
    </rangeSensor>

    <imu>
      <name>imu</name>
      <relativeTo>base_link</relativeTo>
      <position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </position>  
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>3.1415</y>
      </orientation>
      <std>0.00000001</std>
    </imu>

    <pressureSensor>
      <name>pressureSensor</name>
      <relativeTo>base_link</relativeTo>
      <position>
        <x>0</x>
        <y>0</y>
        <z>0.2</z>
      </position>  
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>0</y>
      </orientation>
      <std>0.02</std>
    </pressureSensor>
    
    <gpsSensor>
      <name>GPSSensor</name>
      <relativeTo>base_link</relativeTo>
      <position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </position>  
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>0</y>
      </orientation>
      <std>0.00005</std>
    </gpsSensor>

    <dvlSensor>
      <name>DVLSensor</name>
      <relativeTo>base_link</relativeTo>
      <position>
        <x>-0.75</x>
        <y>0</y>
        <z>0</z>
      </position>  
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>3.9269908169872414</y>
      </orientation>
      <std>0.0015</std>
    </dvlSensor>

    <virtualRangeImage>
      <name>rangeImage</name>
      <relativeTo>part0</relativeTo>
      <resw> 320</resw>
      <resh> 240 </resh>
      <position>
        <x>-0.2</x>
        <y> 0.1 </y>
        <z> 0 </z>
      </position>  
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>1.57 </y>
      </orientation>
      <parameters>
        <fx>257.986</fx>
        <fy>257.341</fy>
        <x0>120</x0>
        <y0>160</y0>
        <f>10</f>
        <n>0.8</n>
        <k>0</k>
      </parameters>

    </virtualRangeImage>

    <multibeamSensor>
      <name>multibeam</name>
      <relativeTo>part0</relativeTo>
      <position>
        <x>-0.2</x>
        <y> 0.1 </y>
        <z> 0 </z>
      </position>  
      <orientation>
        <r>0</r>
        <p>0</p>
        <y>1.57 </y>
      </orientation>
      <initAngle>-60</initAngle>
      <finalAngle>60</finalAngle>
      <angleIncr>0.1</angleIncr>
      <range>10</range>
    </multibeamSensor>

    <simulatedDevices>
      <echo>
        <name>g500_echo1</name>
        <info>Echo example 1</info>
      </echo>
      <echo>
        <name>g500_echo2</name>
        <info>Echo example 2</info>
      </echo>
    </simulatedDevices>
  </vehicle>

  <object>
    <name>terrain</name>
    <file>terrain/CIRS/cirs_trident.osg</file>
    <position>
      <x> 0</x>
      <y> 0 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
    <offsetp>
      <x>-1.5</x>
      <y>-3.0</y>
      <z>0</z>
    </offsetp>
    <offsetr>
      <x> 3.1415</x>
      <y> 0</y>
      <z> -1.57 </z>
    </offsetr>
    <physics>
      <mass> 0 </mass>
      <collisionShapeType> trimesh </collisionShapeType>
    </physics>
  </object>


  <object>
    <name> blackbox </name>
    <file> objects/blackbox_uib_trimesh.osg  </file>
    <position>
      <x> 0</x>
      <y> 0 </y>
      <z> 4.7 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>3.1415</p>
      <y>0</y>
    </orientation>
    <physics>
      <mass> 15 </mass>
      <inertia> 
        <x> 0</x>
        <y> 0 </y>
        <z> 0 </z>
      </inertia>
      <collisionShapeType> box </collisionShapeType>
    </physics>
  </object>

  <rosInterfaces>
    <ROSOdomToPAT>
      <topic> /dataNavigator </topic>
      <vehicleName> girona500 </vehicleName>
      <visualize> 1 </visualize>
    </ROSOdomToPAT>
    <ArmToROSJointState> 
	<topic>/uwsim/joint_state</topic>
	<vehicleName> girona500 </vehicleName>
    </ArmToROSJointState>
    <ROSJointStateToArm> 
	<topic>/uwsim/joint_state_command</topic>
	<vehicleName> girona500 </vehicleName>
    </ROSJointStateToArm>
    <VirtualCameraToROSImage> 
      <cameraName>bowtech1</cameraName>
      <imageTopic> /uwsim/camera1 </imageTopic>
      <infoTopic> /uwsim/camera1_info </infoTopic>
    </VirtualCameraToROSImage>
    <ROSTwistToPAT>
      <topic> /g500/twist</topic>
      <vehicleName> girona500 </vehicleName>
    </ROSTwistToPAT>
    <RangeSensorToROSRange>
      <name>sonar</name>
      <topic> /uwsim/g500/range </topic>
      <rate>10</rate>
    </RangeSensorToROSRange>
    <ROSPoseToPAT>
      <topic> /g500/pose</topic>
      <vehicleName> girona500 </vehicleName>
    </ROSPoseToPAT>
    <ImuToROSImu>
      <name>imu</name>
      <topic>g500/imu</topic>
      <rate>20</rate>
    </ImuToROSImu>
    <PressureSensorToROS>
      <name>pressureSensor</name>
      <topic>g500/pressure</topic>
      <rate>5</rate>
    </PressureSensorToROS>
    <GPSSensorToROS>
      <name>GPSSensor</name>
      <topic>g500/gps</topic>
      <rate>1</rate>
    </GPSSensorToROS>
    <DVLSensorToROS>
      <name>DVLSensor</name>
      <topic>g500/dvl</topic>
      <rate>5</rate>
    </DVLSensorToROS>
    <RangeImageSensorToROSImage> 
      <cameraName>rangeImage</cameraName>
      <imageTopic> /uwsim/rangecamera </imageTopic>
      <infoTopic> /uwsim/rangecamera_info </infoTopic>
    </RangeImageSensorToROSImage>
    <multibeamSensorToLaserScan>
      <name>multibeam</name>
      <topic>g500/multibeam</topic>
    </multibeamSensorToLaserScan>
    <SimulatedDeviceROS>
      <echoROS>
        <name>g500_echo1</name>
        <topic>g500/echo1</topic>
        <rate>1</rate>
      </echoROS>
    </SimulatedDeviceROS>
    <SimulatedDeviceROS>
      <echoROS>
        <name>g500_echo2</name>
        <topic>g500/echo2</topic>
        <rate>1</rate>
      </echoROS>
    </SimulatedDeviceROS>
  </rosInterfaces>
</UWSimScene>
